name: E2E Test
on: [push, pull_request]

jobs:
  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create .terraformrc
        run: |
          cat >.terraformrc << EOF
          provider_installation {
            dev_overrides {
              "1Password/onepassword" = "${{ github.workspace }}/dist"
            }

            # For all other providers, install them directly from their origin provider
            # registries as normal. If you omit this, Terraform will _only_ use
            # the dev_overrides block, and so no other providers will be available.
            direct {}
          }
          EOF

      - name: Content .terraforrc
        run: cat .terraformrc

      - name: List dirs
        run: ls -la

      - name: Prepare(init) working directory
        run: terraform init

      - name: Terraform Plan
        working-directory: e2e/login-item
        run: terraform plan -no-color
